
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 07 10:21:16 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 21;
  public static final int NAMESPACE = 48;
  public static final int NUMCONST = 40;
  public static final int USING = 50;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 17;
  public static final int DECR = 31;
  public static final int VECE_JEDN = 27;
  public static final int DESNA_UGL = 20;
  public static final int FOR = 46;
  public static final int MINUS = 25;
  public static final int STATIC = 49;
  public static final int RPAREN = 7;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int JEDNAKO = 34;
  public static final int COMMA = 8;
  public static final int CLASS = 13;
  public static final int DIV = 38;
  public static final int PLUS = 24;
  public static final int IF = 44;
  public static final int THIS = 47;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 11;
  public static final int SLEDI = 36;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int MUL = 37;
  public static final int TACKA_TACKA = 16;
  public static final int MOD = 39;
  public static final int INKR = 30;
  public static final int IDENT = 43;
  public static final int BREAK = 18;
  public static final int VOID = 12;
  public static final int MANJE = 28;
  public static final int ELSE = 45;
  public static final int LBRACE = 3;
  public static final int VECE = 26;
  public static final int READ = 22;
  public static final int NEJEDN = 35;
  public static final int CHARCONST = 41;
  public static final int TACKA = 15;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 42;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int LEVA_UGL = 19;
  public static final int MANJE_JEDN = 29;
  public static final int PRINT = 9;
}

