
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 07 10:20:56 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
	//kljucne reci 
	
		 public static final int PROG = 1;
		 public static final int BREAK = 2;
		 public static final int CLASS = 3;
		 public static final int ELSE = 4;
		 public static final int CONST = 5;
		 public static final int IF = 6;
		 public static final int NEW = 7;
		 public static final int PRINT = 8;
		 public static final int READ = 9;
		 public static final int VOID = 10;
		 public static final int RETURN = 11;
		 public static final int EXTENDS = 12;
		 public static final int CONTINUE = 13;
		 public static final int THIS = 14;
		 public static final int FOR = 15;
		 
		 public static final int NAMESPACE = 16;
		 public static final int STATIC = 17;
		 
		 //tokeni
		 
		 public static final int IDENT = 18;
		 public static final int BOOLCONST = 19;
		 public static final int CHARCONST = 20;
		 public static final int NUMCONST = 21;
		 
		 //operatori
		 
		 public static final int PLUS = 22;
		 public static final int MINUS = 23;
		 public static final int MUL = 24;
		 public static final int DIV = 25;
		 public static final int MOD  = 26;
		 public static final int EQUAL = 27;
		 public static final int COMMA = 28;
		 public static final int SEMI = 29;
		 public static final int LPAREN = 30;
		 public static final int RPAREN = 31;
		 public static final int LBRACE = 32;
		 public static final int RBRACE = 33;
		 public static final int JEDNAKO = 34;
		  public static final int NEJEDN = 35;
		  public static final int VECE = 36;
		  public static final int VECE_JEDN = 37;
		  public static final int MANJE = 38;
		  public static final int MANJE_JEDN = 39;
		  public static final int AND = 40;
		  public static final int OR = 41;
		  public static final int INKR = 42;
		  public static final int DECR = 43;
		  public static final int TACKA_TACKA = 44;
		  public static final int TACKA = 45;
		  public static final int LEVA_UGL = 46;
		  public static final int DESNA_UGL = 47;
		  public static final int SLEDI = 48;
		  public static final int USING = 49;
		  
		  //komentari i kraj
		  public static final int EOF = 50;
		  public static final int error = 0;
}

